<?php

namespace MembreBundle\Repository;

/**
 * BarkelouRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BarkelouRepository extends \Doctrine\ORM\EntityRepository
{
}
