<?php

namespace ResidenceBundle\Repository;

/**
 * AccueillantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccueillantRepository extends \Doctrine\ORM\EntityRepository
{
}
